### ISSUE TITLE
【第１章演習問題】Chap1-4.ipynbのQ5でCompilation failure: RET_CHECK failure 

### ISSUE THREAD

**Issue by rootphi** [koshian2/MosaicDeeplearningBook#1]
はじめまして。
電子版を購入させていただき、楽しく読んでおります。
Chap1-4.ipynbのQ5で回答通りのコードを実行しても以下のエラーが出ます。

> Train on 390 steps, validate on 79 steps
> Epoch 1/100
> 388/390 [============================>.] - ETA: 0s - loss: 1.6932 - sparse_categorical_accuracy: 0.4323

> ---------------------------------------------------------------------------
> InternalError                             Traceback (most recent call last)
> \<ipython-input-7-a397c95f1afa> in \<module>()
>       4 
>       5     scb = tf.keras.callbacks.LearningRateScheduler(lr_scheduler)
> ----> 6     model.fit(X_train, y_train, validation_data=(X_test, y_test), batch_size=128,steps_per_epoch=50000//128, epochs=100, callbacks=[scb])
>       7 ###
> 
> 11 frames
> /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
>     726         max_queue_size=max_queue_size,
>     727         workers=workers,
> --> 728         use_multiprocessing=use_multiprocessing)
>     729 
>     730   def evaluate(self,
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_distributed.py in fit(self, model, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, **kwargs)
>     683         validation_steps=validation_steps,
>     684         validation_freq=validation_freq,
> --> 685         steps_name='steps_per_epoch')
>     686 
>     687   def evaluate(self,
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_arrays.py in model_iteration(model, inputs, targets, sample_weights, batch_size, epochs, verbose, callbacks, val_inputs, val_targets, val_sample_weights, shuffle, initial_epoch, steps_per_epoch, validation_steps, validation_freq, mode, validation_in_fit, prepared_feed_values_from_dataset, steps_name, **kwargs)
>     437           validation_in_fit=True,
>     438           prepared_feed_values_from_dataset=(val_iterator is not None),
> --> 439           steps_name='validation_steps')
>     440       if not isinstance(val_results, list):
>     441         val_results = [val_results]
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_arrays.py in model_iteration(model, inputs, targets, sample_weights, batch_size, epochs, verbose, callbacks, val_inputs, val_targets, val_sample_weights, shuffle, initial_epoch, steps_per_epoch, validation_steps, validation_freq, mode, validation_in_fit, prepared_feed_values_from_dataset, steps_name, **kwargs)
>     297           else:
>     298             actual_inputs = ins()
> --> 299           batch_outs = f(actual_inputs)
>     300         except errors.OutOfRangeError:
>     301           if is_dataset:
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/distribute/distributed_training_utils.py in execution_function(input_fn)
>     876       def execution_function(input_fn):
>     877         # `numpy` translates Tensors to values in Eager mode.
> --> 878         return [out.numpy() for out in distributed_function(input_fn)]
>     879     else:
>     880       execution_function = distributed_function
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/def_function.py in __call__(self, *args, **kwds)
>     455 
>     456     tracing_count = self._get_tracing_count()
> --> 457     result = self._call(*args, **kwds)
>     458     if tracing_count == self._get_tracing_count():
>     459       self._call_counter.called_without_tracing()
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/def_function.py in _call(self, *args, **kwds)
>     524               *args, **kwds)
>     525       # If we did not create any variables the trace we have is good enough.
> --> 526       return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
>     527 
>     528     def fn_with_cond(*inner_args, **inner_kwds):
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py in _filtered_call(self, args, kwargs)
>    1139          if isinstance(t, (ops.Tensor,
>    1140                            resource_variable_ops.BaseResourceVariable))),
> -> 1141         self.captured_inputs)
>    1142 
>    1143   def _call_flat(self, args, captured_inputs, cancellation_manager=None):
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
>    1222     if executing_eagerly:
>    1223       flat_outputs = forward_function.call(
> -> 1224           ctx, args, cancellation_manager=cancellation_manager)
>    1225     else:
>    1226       gradient_name = self._delayed_rewrite_functions.register()
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py in call(self, ctx, args, cancellation_manager)
>     509               inputs=args,
>     510               attrs=("executor_type", executor_type, "config_proto", config),
> --> 511               ctx=ctx)
>     512         else:
>     513           outputs = execute.execute_with_cancellation(
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
>      65     else:
>      66       message = e.message
> ---> 67     six.raise_from(core._status_to_exception(e.code, message), None)
>      68   except TypeError as e:
>      69     keras_symbolic_tensors = [
> 
> /usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)
> 
> InternalError:  Compilation failure: RET_CHECK failure (third_party/tensorflow/compiler/xla/service/hlo_instruction.cc:2047) ShapeUtil::CompatibleIgnoringFpPrecision(shape(), new_producer->shape()) s32[] is not compatible with u32[]
> 	TPU compilation failed
> 	 [[{{node tpu_compile_succeeded_assert/_9814859852665117289/_5}}]]
> 	Encountered when executing an operation using EagerExecutor. This error cancels all future operations and poisons their output tensors.
> Additional GRPC error information:
> {"created":"@1583968145.100972105","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":" Compilation failure: RET_CHECK failure (third_party/tensorflow/compiler/xla/service/hlo_instruction.cc:2047) ShapeUtil::CompatibleIgnoringFpPrecision(shape(), new_producer->shape()) s32[] is not compatible with u32[]\n\tTPU compilation failed\n\t [[{{node tpu_compile_succeeded_assert/_9814859852665117289/_5}}]]\n\tEncountered when executing an operation using EagerExecutor. This error cancels all future operations and poisons their output tensors.","grpc_status":13} [Op:__inference_distributed_function_60575]
> 
> Function call stack:
> distributed_function -> distributed_function
>

**Comment by koshian2** [comment]
@rootphi 
ご報告ありがとうございます。模範解答を入力して動作を検証したところ、2エポック以降も訓練が進むことを確認しました。以前の原因が考えられます。

### TensorFlowのバージョンは2系になっていない可能性
冒頭の```!pip install tensorflow==2.0.0```を実行しましたでしょうか？　ColabのデフォルトがTF1.15（1系）なので、TFのバージョンの違いでエラーが出る可能性があります。現在の環境のTensorFlowのバージョンを確認するには、

```python
import tensorflow as tf
print(tf.__version__)
```

を実行してみてください。ランタイムがリセットされるとTFのバージョンが戻ってしまいますので、リセットされたらこれを実行し直してください（上から実行し直すのが早いです）。

### TPUが何らかの通信エラーを起こしている可能性
こちらのほうがあり得るかなと思っているのですが（自分も訓練中何回か遭遇しました）、たまにColab TPUが通信エラーを起こすことがあります。無料で提供している以上仕方ないところはあるのですが、その場合はお手数ですが「ランタイム→ランタイムの再起動」もしくは「ランタイム→ランタイムを出荷状態にリセット」を実行してみてください。

ランタイムのリセットをすると環境がすべてデフォルトに戻ってしまいますので、最初からセルを実行する必要があります。

Cp1-4は最初にしては難しめの問題なので、ハマってしまったら無理をせず次の章に進むことをおすすめします。

**Comment by rootphi** [comment]
返信ありがとうございます。
tf.__version__は2.0.0でしたが、
「ランタイムを出荷状態にリセット」した後に、上のセルから順に実行したら、epoch２以降も進行しました。
的確なご指導、助かりました。
