### ISSUE TITLE
Chap1-4.ipynbのTPU初期化のおまじないが通りません

### ISSUE THREAD

**Issue by hh-TDA** [koshian2/MosaicDeeplearningBook#3]
```
import tensorflow as tf
tf.__version__
```
'2.0.0'
```
import tensorflow as tf
import os
tpu_grpc_url = "grpc://" + os.environ["COLAB_TPU_ADDR"]
tpu_cluster_resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu_grpc_url)
tf.config.experimental_connect_to_cluster(tpu_cluster_resolver) # TF2.0の場合
tf.tpu.experimental.initialize_tpu_system(tpu_cluster_resolver) # TF2.0の場合、今後experimentialが取れる可能性がある    
strategy = tf.distribute.experimental.TPUStrategy(tpu_cluster_resolver) 
```
- 以下にスクリーンショットを貼ります  

![image](https://user-images.githubusercontent.com/40915832/78773318-0443d680-79ce-11ea-9048-8746044873fa.png)

![image](https://user-images.githubusercontent.com/40915832/78773384-1c1b5a80-79ce-11ea-88da-120493c96424.png)

**Comment by koshian2** [comment]
@hh-TDA 
ご報告ありがとうございます。エラーの再現を確認いたしました。ColabのデフォルトのTFバージョンが2.2.0rc2に変わったためだと思われます（演習問題を作ったときはTF1.15がデフォルトだった）

解決法としては、「!pip install tensorflow==2.0.0」を実行したあと、**ランタイム→ランタイムを再起動**を行ってください。これを行うとエラーが消えてるのを確認しました。「ランタイムを再起動してくれ」というメッセージやボタンは出ませんが、再起動必須のようです。

**Comment by hh-TDA** [comment]
早速のご返答、ありがとうございます
ランタイムの再起動を行いました
![image](https://user-images.githubusercontent.com/40915832/78837536-40f3ea00-7a2f-11ea-905e-5a6bd13c24c4.png)

エラーは出ませんでした
ありがとうございます
